version: '3.9'

services:
  whoami:
    image: traefik/whoami:latest
    # command:
       # It tells whoami to start listening on 2001 instead of 80
      #  - --port=2001
      #  - --name=iamfoo
    # ports:
    #   - "80:80"
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "--providers.docker.network=traefiknet"
    networks:
      - traefiknet
networks:
  traefiknet:
    external: true