version: '3'

services:

  mautic:
    image: mautic/mautic:v4
    # volumes:
    #   - ./mautic/html:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=password
      - MAUTIC_DB_NAME=database
      - MAUTIC_RUN_CRON_JOBS=false
    depends_on:
      - mauticdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mautic.rule=Host(`mautic.local`)"
      - "traefik.http.services.mautic.loadbalancer.server.port=80"
      - "--providers.docker.network=traefiknet"
    networks:
      - traefiknet
      - mauticnet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  
  
  mauticdb:   
    image: mariadb:latest # not use percona (memory overflow)
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    # volumes:
    #   - ./mautic/mauticdb/data:/var/lib/mysql
    networks:
      - dbsnet
      - mauticnet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  


networks:
  traefiknet:
    external: true
  dbsnet:
    external: true
  mauticnet:
    external: true