version: '3'

services:


  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=n8ndb
      - DB_MYSQLDB_DATABASE=database
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=password
    # volumes:
    #   - n8n_storage:/home/node/.n8n
    command: n8n start --tunnel
    depends_on:
      - n8ndb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.local`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "--providers.docker.network=traefiknet"
    networks:
      - traefiknet
      - n8nnet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  
  
  n8ndb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    # volumes:
    #   - ./n8n/n8ndb/data:/var/lib/mysql
    networks:
      - dbsnet
      - n8nnet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  


networks:
  traefiknet:
    external: true
  dbsnet:
    external: true
  n8nnet:
    external: true