version: '3'

services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=traefiknet"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - $PWD/traefik.toml:/etc/traefik/traefik.toml
      # - $PWD/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefiknet
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4096M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  

networks:
  traefiknet:
    external: true
