version: '3'

services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=traefiknet"
    ports: 
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - $PWD/traefik.toml:/etc/traefik/traefik.toml
      # - $PWD/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefiknet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  

networks:
  traefiknet:
    external: true
