version: '3'

services:


  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - 80
    environment:
      - PMA_ARBITRARY=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.local`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "--providers.docker.network=traefiknet"
    networks:
      - traefiknet
      - dbsnet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  
    

networks:
  dbsnet:
    external: true
  traefiknet:
    external: true
