version: '3'

services:

  wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=wordpressdb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=database
      - WORDPRESS_DB_PASSWORD=password
    depends_on:
      - wordpressdb
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "--providers.docker.network=traefiknet"
    networks:
      - traefiknet
      - wordpressnet
    # volumes:
    #   - ./wordpress/html:/var/www/html    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  

  wordpressdb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    # volumes:
    #   - ./wordpress/wordpressdb/data:/var/lib/mysql
    networks:
      - dbsnet
      - wordpressnet
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M  

networks:
  traefiknet:
    external: true
  dbsnet:
    external: true
  wordpressnet:
    external: true